************************************************************************
* header:                 LIE ALGEBRAIC                                *
*  Lie algebraic manipulations: Poisson brackets, etc.                 *
************************************************************************
c
      subroutine brkts(h)
c
c     computes poisson brackets of
c     transfer map generator h with each
c     dynamical variable  z(i)
c     pbh(j,i=1,6) contains j-th element
c     of array of coefficients of [h, (i)]
c     pbh(j,i=7,12) contains j-th
c     element of array of coefficients
c     of [h,[h, (i)]].
c     Written by D. Douglas, ca 1982
c
      include 'impli.inc'
      include 'param.inc'
      dimension h(monoms),pb1(monoms),pb2(monoms),pb3(monoms),
     *          pb4(monoms),pb5(monoms)
      include 'pbkh.inc'
c
c     initialize arrays
c
      do 10 i=1,monoms
      pb1(i)=0.0d0
      pb2(i)=0.0d0
      pb3(i)=0.0d0
      do 20 j=1,12
      pbh(i,j)=0.0d0
   20 continue
   10 continue
c
c     compute poisson brackets and store in pbh
c
      m=2
      n=3
      do 30 j=1,6
      k=j+6
      call svpbkt(h,n,j,1,pb1)
      call pbkt(h,n,pb1,m,pb3)
      call pbkt(h,n,pb3,n,pb5)
      do 40 i=7,27
      pbh(i,j)=pbh(i,j)+pb1(i)
   40 continue
      do 45 i=28,83
      pbh(i,k)=pbh(i,k)+pb3(i)
   45 continue
      do 47 i=84,209
      pbh(i,k)=pbh(i,k)+pb5(i)
   47 continue
   30 continue
      m=3
      n=4
      do 50 j=1,6
      call svpbkt(h,n,j,1, pb2)
      call pbkt(h,m,pb2,m,pb4)
      do 60 i=28,83
      pbh(i,j)=pbh(i,j)+pb2(i)
   60 continue
      do 65 i=84,209
      pbh(i,j)=pbh(i,j)+pb4(i)
   65 continue
   50 continue
      return
      end
c
***********************************************************************
c
      subroutine clear(h,mh)
c Clears to zero the polynomials h and the matrix mh.
c Written by Liam Healy, June 12, 1984.  Modified by Alex Dragt
c 9 June 1988.
      include 'param.inc'
      double precision mh(6,6),h(monoms)
c  Clear out polynomial coefficients:
      do 120 i=1,monoms
  120 h(i)=0.
c  Clear out matrix:
      do 100 i=1,6
      do 100 j=1,6
  100 mh(i,j)=0.
      return
      end
c
***********************************************************************
c
      subroutine concat(f,mf,g,mg,h,mh)
c     concatenates a map with linear piece
c     represented by a matrix mf and nonlinearities
c     represented by exp:f:, with a map whose
c     linear piece has matrix representation mg
c     and whose nonlinearities are represented by exp:g:
c
c     the result is a map with linearities possessing
c     a matrix representation mh=mg*mf
c     and with nonlinearities generated by exp:h:
c
c     the "f" map is assumed to occur first in the beamline
c     the "g" map is encountered second
c     that is, one has the map relation h=f*g
c
c     Written by David Douglas, ca 1982
c     Modified by Alex Dragt 24 June 1988 so that the routine
c     still works even when the map h,mh is one of the maps
c     f,mf or g,mg.    
c
      include 'impli.inc'
      include 'param.inc'
c
c calling arrays
      dimension f(monoms),g(monoms),h(monoms)
      double precision mf(6,6),mg(6,6),mh(6,6)
c
c working arrays
      dimension t1(monoms),t2(monoms)
      double precision mt1(6,6),mt2(6,6)
c
      include 'symp.inc'
c
c compute mt1=mg*mf and mt2=mgtransposed*jm
c
      call mclear(mt1)
      call mclear(mt2)
      do 40 j=1,6
      do 30 i=1,6
      do 20 k=1,6
      mt1(i,j)=mt1(i,j)+mg(i,k)*mf(k,j)
      mt2(i,j)=mt2(i,j)+mg(k,i)*jm(k,j)
   20 continue
   30 continue
   40 continue
c
c set mh=mt1
c
      do 31 j=1,6
      do 21 i=1,6
      mh(i,j)=mt1(i,j)
   21 continue
   31 continue
c
c compute mt1=jmtransposed*mt2=inverse of mg
c
      call mclear(mt1)
      do 42 j=1,6
      do 32 i=1,6
      do 22 k=1,6
      mt1(i,j)=mt1(i,j)+jm(k,i)*mt2(k,j)
   22 continue
   32 continue
   42 continue
c
c compute t1=result of transforming f by mt1
c
      call xform(f,3,mt1,0,t1)
      call xform(f,4,mt1,1,t1)
c
c compute t2=[t1,g]
c
      call pbkt(t1,3,g,3,t2)
c
c compute degree-three coefficients
c
      do 50 k=28,83
      h(k)=g(k)+t1(k)
   50 continue
c
c compute degree-four coefficients
c
      do 60 k=84,209
      h(k)=g(k)+t1(k)+t2(k)/2.d0
   60 continue
c
      return
      end
c
********************************************************************
c
      subroutine cpadd(fa,ga,ha)
c this is a subroutine for computing the sum of two polynomials
c Written by Alex Dragt, Fall 1986
      include 'impli.inc'
      include 'param.inc'
      dimension fa(monoms),ga(monoms),ha(monoms)
c
c perform calculation
      do 10 j=1,monoms
      ha(j)=fa(j)+ga(j)
   10 continue
c
      return
      end
c
************************************************************************
c
      subroutine cpdnf(pow,fa,fm,ga,gm)
c this subroutine computes the power of a dynamic normal form map:
c mapg=(mapf)**pow
c Written by Alex Dragt, Fall 1986
c
      include 'impli.inc'
      include 'param.inc'
c
c Calling arrays 
      dimension fa(monoms),ga(monoms)
      dimension fm(6,6),gm(6,6)
c
c Local arrays
      dimension ta(monoms)
c
c clear output array
      call clear(ta,gm)
c
c begin calculation
c
c compute phase advances
      cwx=fm(1,1)
      swx=fm(1,2)
      wx=atan2(swx,cwx)
      cwy=fm(3,3)
      swy=fm(3,4)
      wy=atan2(swy,cwy)
      cwt=fm(5,5)
      swt=fm(5,6)
      wt=atan2(swt,cwt)
c compute new quantities
      pwx=pow*wx
      cpwx=cos(pwx)
      spwx=sin(pwx)
      pwy=pow*wy
      cpwy=cos(pwy)
      spwy=sin(pwy)
      pwt=pow*wt
      cpwt=cos(pwt)
      spwt=sin(pwt)
c compute new matrix
      gm(1,1)=cpwx
      gm(1,2)=spwx
      gm(2,1)=-spwx
      gm(2,2)=cpwx
      gm(3,3)=cpwy
      gm(3,4)=spwy
      gm(4,3)=-spwy
      gm(4,4)=cpwy
      gm(5,5)=cpwt
      gm(5,6)=spwt
      gm(6,5)=-spwt
      gm(6,6)=cpwt
c compute polynomials of old normal form map in dynamic resonance basis
      call ctodr(fa,ga)
c pick out those terms which are allowed to be nonzero
      ta(84)=ga(84)
      ta(85)=ga(85)
      ta(86)=ga(86)
      ta(87)=ga(87)
      ta(88)=ga(88)
      ta(89)=ga(89)
c compute polynomials of new map in dynamic resonance basis
      call csmul(pow,ta,ta)
c transform back to cartesian basis
      call drtoc(ta,ga)
c
      return
      end
c
********************************************************************
c
      subroutine cpmul(fa,ga,ha)
c Subroutine for computing the product of polynomials
c Written by Alex Dragt, Fall 1986
      include 'impli.inc'
      include 'param.inc'
      dimension fa(monoms),ga(monoms),ha(monoms)
c
c perform calculation
      do 10 nf=1,3
      do 20 ng=1,3
      if ((nf+ng).le.4) then
      call pprod(fa,nf,ga,ng,ha)
      endif
   20 continue
   10 continue
c
      return
      end
c
************************************************************************
c
      subroutine cpsnf(pow,fa,fm,ga,gm)
c this subroutine computes the power of a static normal form map:
c mapg=(mapf)**pow
c Written by Alex Dragt, Fall 1986
c
      include 'impli.inc'
      include 'param.inc'
c
c Calling arrays 
      dimension fa(monoms),ga(monoms)
      dimension fm(6,6),gm(6,6)
c
c Local arrays
      dimension ta(monoms)
c
c clear output array
      call clear(ta,gm)
c
c begin calculation
c
c compute phase advances
      cwx=fm(1,1)
      swx=fm(1,2)
      wx=atan2(swx,cwx)
      cwy=fm(3,3)
      swy=fm(3,4)
      wy=atan2(swy,cwy)
c compute momentum compaction
      wt=fm(5,6)
c compute new quantities
      pwx=pow*wx
      cpwx=cos(pwx)
      spwx=sin(pwx)
      pwy=pow*wy
      cpwy=cos(pwy)
      spwy=sin(pwy)
      pwt=pow*wt
c compute new matrix
      gm(1,1)=cpwx
      gm(1,2)=spwx
      gm(2,1)=-spwx
      gm(2,2)=cpwx
      gm(3,3)=cpwy
      gm(3,4)=spwy
      gm(4,3)=-spwy
      gm(4,4)=cpwy
      gm(5,5)=1.d0
      gm(5,6)=pwt
      gm(6,6)=1.d0
c compute polynomials of old normal form map in static resonance basis
      call ctosr(fa,ga)
c pick out those terms which are allowed to be nonzero
      ta(28)=ga(28)
      ta(29)=ga(29)
      ta(30)=ga(30)
      ta(84)=ga(84)
      ta(85)=ga(85)
      ta(86)=ga(86)
      ta(87)=ga(87)
      ta(88)=ga(88)
      ta(89)=ga(89)
c compute polynomials of new map in static resonance basis
      call csmul(pow,ta,ta)
c transform back to cartesian basis
      call srtoc(ta,ga)
c
      return
      end
c
********************************************************************
c
      subroutine csmul(scalar,fa,ga)
c this subroutine computes the scalar multiple of a polynomial
c Written by Alex Dragt, Fall 1986
      include 'impli.inc'
      include 'param.inc'
      dimension fa(monoms),ga(monoms)
c
c perform calculation
      do 10 j=1,monoms
      ga(j)=scalar*fa(j)
   10 continue
c
      return
      end
c
************************************************************
c
      subroutine cpsp(f,g,ans1,ans2,ans3,ans4)
c  this subroutine computes the scalar product of the two polynomials
c  f and g.
c  Written by Alex Dragt 10/23/89
c
      include 'impli.inc'
      include 'param.inc'
      include 'expon.inc'
c
c  calling arrays
      dimension f(209), g(209)
c
      integer jf(6),jg(6)
c
c  compute inner products
c
c  first order part
c
      ans1=0.d0
      do 10 indf=1,6
      do 10 indg=1,6
      test=f(indf)*g(indg)
      if (test .ne. 0.d0) then
      do 12 k=1,6
      jf(k)=expon(k,indf)
      jg(k)=expon(k,indg)
   12 continue
      call msp(jf,jg,val)
      ans1=ans1+test*val
      endif
   10 continue
      ans1=ans1/3.d0
c
c  second order part
c
      ans2=0.d0
      do 20 indf=7,27
      do 20 indg=7,27
      test=f(indf)*g(indg)
      if (test .ne. 0.) then
      do 22 k=1,6
      jf(k)=expon(k,indf)
      jg(k)=expon(k,indg)
   22 continue
      call msp(jf,jg,val)
      ans2=ans2+test*val
      endif
   20 continue
      ans2=ans2/12.d0
c
c  third order part
c
      ans3=0.d0
      do 30 indf=28,83
      do 30 indg=28,83
      test=f(indf)*g(indg)
      if (test .ne. 0.d0) then
      do 32 k=1,6
      jf(k)=expon(k,indf)
      jg(k)=expon(k,indg)
   32 continue
      call msp(jf,jg,val)
      ans3=ans3+test*val
      endif
   30 continue
      ans3=ans3/60.d0
c
c  fourth order part
c
      ans4=0.d0
      do 40 indf=84,209
      do 40 indg=84,209
      test=f(indf)*g(indg)
      if (test .ne. 0.) then
      do 42 k=1,6
      jf(k)=expon(k,indf)
      jg(k)=expon(k,indg)
   42 continue
      call msp(jf,jg,val)
      ans4=ans4+test*val
      endif
   40 continue
      ans4=ans4/360.d0
c
      return
      end
c
***********************************************************************
c
      subroutine evalf(zi,h,val2,val3,val4)
c this subroutine computes the value of the function h(zi)
c Written by Alex Dragt, Fall 1986, based on work of F. Neri
      include 'impli.inc'
      include 'param.inc'
      dimension zi(6)
      dimension h(monoms),vect(monoms)
      include 'ind.inc'
c compute vector containing values of basis monomials
      call evalm(zi,vect)
c
c the following code has been commented out since it is replaced
c by the use of evalm
c compute linear monomials
c      do 10 i=1,6
c   10 vect(i) = zi(i)
c compute higher order monomials
c      do 20 i = 7,monoms
c   20 vect(i) = vect(index1(i))*vect(index2(i))
c
c compute value of h
      val2=0.d0
      do 30 i=1,27
   30 val2=val2+h(i)*vect(i)
      val3=val2
      do 40 i=28,83
   40 val3=val3+h(i)*vect(i)
      val4=val3
      do 50 i=84,209
   50 val4=val4+h(i)*vect(i)
      return
      end
c
***********************************************************************
c
      subroutine evalm(zi,vect)
c this subroutine computes the values of the basis 
c monomials and stores them in the vector vect.
c Written by Alex Dragt, 1 July 1991, based on work of F. Neri
c
      include 'impli.inc'
      include 'param.inc'
      include 'ind.inc'
c
c calling arrays
      dimension zi(6)
      dimension vect(monoms)
c
c compute linear monomials
      do 10 i=1,6
   10 vect(i) = zi(i)
c compute higher order monomials
      do 20 i = 7,monoms
   20 vect(i) = vect(index1(i))*vect(index2(i))
c
      return
      end
c
      subroutine evalm5(zi,vect)
c this subroutine computes the values of the basis 
c monomials and stores them in the vector vect.
c Written by Alex Dragt, 1 July 1991, based on work of F. Neri
c Modified to generate <5> and <6>, by Johannes van Zeijts, 11 November 1991.
c
      include 'impli.inc'
      include 'param.inc'
      include 'ind.inc'
c
c calling arrays
      dimension zi(6)
      dimension vect(monoms5)
c
c compute linear monomials
      do 10 i=1,6
   10 vect(i) = zi(i)
c compute higher order monomials
      do 20 i = 7,monoms5
   20 vect(i) = vect(index1(i))*vect(index2(i))
c
      return
      end
c
******************************************************************
c
      subroutine fxform(ga,gm,fa,ha)
c This is a subroutine for transforming a function f.
c That is, it  computes h=exp(:g:)f where f is given
c by f=f1+f2+f3+f4 and exp(:g:) denotes a general map.
c Presently f1 is transformed only by the linear part of exp(:g:).
c Written by Alex Dragt, Fall 1986.
c Modified by Alex Dragt, 10/28/89.
c
      include 'impli.inc'
      include 'param.inc'
c
c Calling arrays
c
      dimension ga(monoms),fa(monoms),ha(monoms)
      dimension gm(6,6)
c
c Working arrays
c
      dimension t1a(monoms),t2a(monoms),t3a(monoms)
      dimension tm(6,6)
c
c clear arrays
c
      call clear(t1a,tm)
      call clear(t2a,tm)
      call clear(t3a,tm)
      call clear(ha,tm)
c
c compute various poisson brackets
c
c compute [g3,f2]
      call pbkt(ga,3,fa,2,t1a)
c compute [g3,f3]
      call pbkt(ga,3,fa,3,t2a)
c compute [g3,[g3,f2]]
      call pbkt(ga,3,t1a,3,t3a)
c compute [g4,f2]
      call pbkt(ga,4,fa,2,t1a)
c
c accumulate results
c
c set up first order part
      do 5 i=1,6
    5 t1a(i)=fa(i)
c set up second order part
      do 10 i=7,27
   10 t1a(i)=fa(i)
c set up third order part
      do 20 i=28,83
   20 t1a(i)=fa(i) + t1a(i)
c set up fourth order part
      do 30 i=84,209
   30 t1a(i)=fa(i) + t2a(i) + t3a(i)/2.d0 + t1a(i)
c
c transform results by gm
c
      call xform(t1a,1,gm,0,ha)
      call xform(t1a,2,gm,1,ha)
      call xform(t1a,3,gm,1,ha)
      call xform(t1a,4,gm,1,ha)
c
      return
      end
c
***********************************************************************
c
      subroutine mapmap(rh,rmh,th,tmh)
c  Written by Rob Ryne, ca 1982
      include 'impli.inc'
      include 'param.inc'
      dimension rh(monoms),th(monoms),rmh(6,6),tmh(6,6)
      do 10 i=1,6
      do 10 j=1,6
   10 tmh(i,j)=rmh(i,j)
      do 20 i=1,monoms
   20 th(i)=rh(i)
      return
      end
c
***********************************************************************
c
      subroutine matify(matrix,f2)
c  Computes the matrix that corresponds to :f2:.
c  It is written in a simple-minded manner to keep execution time short.
c  Written by Liam Healy, May 29, 1985.
c
c----Variables----
c     implicit none
c matrix = matrix supplied
      double precision matrix(6,6)
c f2 = array of coefficients giving f2 values (others are ignored)
      double precision f2(*)
c
c----Routine----
      matrix(1,1)=-f2(8)
      matrix(1,2)=-2.*f2(13)
      matrix(1,3)=-f2(14)
      matrix(1,4)=-f2(15)
      matrix(1,5)=-f2(16)
      matrix(1,6)=-f2(17)
      matrix(2,1)=2.*f2(7)
      matrix(2,2)=f2(8)
      matrix(2,3)=f2(9)
      matrix(2,4)=f2(10)
      matrix(2,5)=f2(11)
      matrix(2,6)=f2(12)
      matrix(3,1)=-f2(10)
      matrix(3,2)=-f2(15)
      matrix(3,3)=-f2(19)
      matrix(3,4)=-2.*f2(22)
      matrix(3,5)=-f2(23)
      matrix(3,6)=-f2(24)
      matrix(4,1)=f2(9)
      matrix(4,2)=f2(14)
      matrix(4,3)=2.*f2(18)
      matrix(4,4)=f2(19)
      matrix(4,5)=f2(20)
      matrix(4,6)=f2(21)
      matrix(5,1)=-f2(12)
      matrix(5,2)=-f2(17)
      matrix(5,3)=-f2(21)
      matrix(5,4)=-f2(24)
      matrix(5,5)=-f2(26)
      matrix(5,6)=-2.*f2(27)
      matrix(6,1)=f2(11)
      matrix(6,2)=f2(16)
      matrix(6,3)=f2(20)
      matrix(6,4)=f2(23)
      matrix(6,5)=2.*f2(25)
      matrix(6,6)=f2(26)
      return
      end
c
***********************************************************************
c
      subroutine mclear(mh)
c Clears to zero the matrix mh.
c Written by Alex Dragt, June 9, 1988.
      double precision mh(6,6)
c
      do 100 i=1,6
      do 100 j=1,6
  100 mh(i,j)=0.d0
      return
      end
c
***********************************************************************
c
      subroutine minv(fm)
c  Returns the inverse of the matrix fm on the
c  assumption that fm is symplectic.
c  Written by Alex Dragt, 4 October 1989.
c
      include 'impli.inc'
      include 'symp.inc'
c
c  Calling array
      dimension fm(6,6)
c
c  Temporary arrays
      dimension temp(6,6)
c
c----Routine----
c
c  Calculate (fm transpose)*jm
c
      call mclear(temp)
      do 120 j=1,6
      do 120 k=1,6
      do 120 l=1,6
  120  temp(j,k)=temp(j,k)+fm(l,j)*jm(l,k)
c
c  Calculate (jm transpose)*(fm transpose)*jm
c
      call mclear(fm)
      do 140 j=1,6
      do 140 l=1,6
      do 140 k=1,6
  140  fm(j,k)=fm(j,k)+jm(l,j)*temp(l,k)
c
      return
      end
c
***********************************************************************
c
      subroutine msp(j1,j2,val)
c  Calculated the scalar product of two monomials having exponent
c  arrays j1 and j2.
c  Written by Alex Dragt 10/22/89
c
      include 'impli.inc'
c
c  calling arrays
      integer j1(6),j2(6)
c
      integer jt(6)
c
      do 10 i=1,6
   10 jt(i)=j1(i)+j2(i)
      call s5i(jt,val)
c
      return
      end
c
***********************************************************************
c
      subroutine pbkt(f,ordf,g,ordg,pb)
c  Calculates the Poisson Bracket of the order ordf part of f with
c  the order ordg part of g, leaving the result in pb.
c  Written by Liam Healy, November 26, 1984.
c
c----Variables----
      include 'param.inc'
c  f,g,pb = two arrays and their Poisson bracket
      double precision f(*),g(*),pb(*)
c  ordf,ordg = order desired from f and g
      integer ordf,ordg
c  indf,indg,indpb = index in f,g and pb
      integer indf,indg,indpb
c  pr = array of exponents for the product of f(indf) and g(indg)
c  prd =copy of pr
c  prx, prp = exponents of particular x, p variables, from pr
      integer pr(6),prd(6),prx,prp
c  xvb, pvb, vbl = x variable, p variable (pvb=xvb+1), variable number
      integer xvb,pvb,vbl
      include 'expon.inc'
      include 'lims.inc'
c
c----Routine----
c  initialize array pb
      do 80 indpb=bottom(ordf+ordg-2),top(ordf+ordg-2)
   80   pb(indpb)=0.
c  pick individual indf and indg, find what element of pb it affects,
c  and calculate the new value.  Loop for all indeces in the specified
c  orders.
      do 100 indf=bottom(ordf),top(ordf)
        if (f(indf).ne.0.) then
          do 120 indg=bottom(ordg),top(ordg)
            if (g(indg).ne.0.) then
c               load sum of exponents into pr
              do 140 vbl=1,6
  140           pr(vbl)=expon(vbl,indf)+expon(vbl,indg)
              do 160 xvb=1,5,2
c                 go through three axes; for each one that pb can
c                 be taken, modify appropriate element of pb.
                pvb=xvb+1
                do 180 vbl=1,6
  180             prd(vbl)=pr(vbl)
                prx=prd(xvb)
                prp=prd(pvb)
                if (prx*prp.gt.0) then
                  prd(xvb)=prx-1
                  prd(pvb)=prp-1
                  indpb=ndex(prd)
                  pb(indpb)=pb(indpb)+f(indf)*g(indg)
     #               *(expon(xvb,indf)*expon(pvb,indg)
     #               -expon(pvb,indf)*expon(xvb,indg))
                endif
  160         continue
            endif
  120     continue
        endif
  100 continue
      return
      end
c
************************************************************************
c
      subroutine polr(fa,fm,rm,pdsm,reval,revec)
c  This subroutine finds the polar decomposition of a symplectic map.
c  fa,fm is the incoming map, and is left unchanged.
c  rm and pdsm are its orthogonal (rotation) and positive definite
c  symmetric factors.  It is assumed that fm has the factorization
c  fm=pdsm*rm.
c  reval and revec are the eigenvalues and eigenvector array for pdsm.
c  Written by Alex Dragt, Fall 1986.  Modified 9/4/91 by Alex Dragt.
c
      include 'impli.inc'
      include 'param.inc'
c
c Calling arrays
      dimension fa(monoms)
      dimension fm(6,6),rm(6,6),pdsm(6,6),reval(6),revec(6,6)
c
c Local arrays
      dimension ta(monoms)
      dimension t1m(6,6),t2m(6,6)
c
c clear array
      call clear(ta,t1m)
c
c begin computation
c
c  computation of positive definite symmetric factor
c  along with its eigenvalues and eigenvectors
c
c  find fm*(fm transpose)
      call matmat(fm,t1m)
      call mtran(t1m)
      call mmult(fm,t1m,t2m)
c  extract square root
      call seig6(t2m,reval,revec)
      call mclear(t2m)
      do 10 i=1,6
      reval(i)=sqrt(reval(i))
      t2m(i,i)=reval(i)
   10 continue
      call matmat(revec,t1m)
      call inv(ta,t1m)
      call sndwch(ta,t1m,ta,t2m,ta,pdsm)
c
c  computation of orthogonal (rotation) factor based on the relation
c  exp(:f2c:)=(script M)(exp:-f2a:)
c
      call matmat(pdsm,t1m)
      call inv(ta,t1m)
      call concat(ta,fm,ta,t1m,ta,rm)
c
      return
      end
c
************************************************************************
c
      subroutine pprod(a,na,b,nb,c)
c this subroutine computes the product of two homogeneous
c polynomials: c=a*b
c Written by Alex Dragt, Fall 1986, based on work of F. Neri
      include 'impli.inc'
      include 'param.inc'
      include 'expon.inc'
      include 'lims.inc'
c
c calling arrays
c
      dimension a(monoms),b(monoms),c(monoms),l(6)
c
      do 200 ia=bottom(na),top(na)
           if(a(ia).eq.0.d0) goto 200
           do 20 ib = bottom(nb),top(nb)
               if(b(ib).eq.0.d0) goto 20
               do 2 m=1,6
                   l(m) = expon(m,ia) +  expon(m,ib)
   2           continue
               n = ndex(l)
               c(n) = c(n) + a(ia)*b(ib)
  20       continue
 200  continue
c
      return
      end
c
***********************************************************************
c
      subroutine s2f(revec,k1,k2,val)
c  this subroutine evaluates the symplectic 2-form assiciated with J
c  Written by Alex Dragt, Fall 1986
      include 'impli.inc'
      dimension revec(6,6)
c
c  begin calculation
      val=0.d0
      do 10 ip=2,6,2
      iq=ip-1
      val=val+revec(iq,k1)*revec(ip,k2)-revec(ip,k1)*revec(iq,k2)
   10 continue
c
      return
      end
c
***********************************************************************
c
      subroutine s5i(j,ans)
c Calculates the integral over S5 of the monomial having exponents
c stored in j.
c Written by Alex Dragt 10/22/89
c
      include 'impli.inc'
c
c     calling array
      integer j(6)
c
      dimension anst(6)
c
      ans=0.
      do 10 i=1,6
      tans=0.d0
      ji=j(i)
      if (ji .eq. 0) tans=1.d0
      if (ji .eq. 2) tans=1.d0/2.d0
      if (ji .eq. 4) tans=3.d0/4.d0
      if (ji .eq. 6) tans=15.d0/8.d0
      if (ji .eq. 8) tans=105.d0/16.d0
      if (tans .eq. 0.d0) return
      anst(i)=tans
   10 continue
      ans=anst(1)*anst(2)*anst(3)*anst(4)*anst(5)*anst(6)
c
      return
      end
c
***********************************************************************
c
      subroutine smtof(scale,tm,ta)
c converts the symmetric matrix scale*tm to the array ta.
c written by Alex Dragt 22 May 1991
c
      include 'impli.inc'
      include 'param.inc'
c
c calling arrays
      dimension ta(monoms), tm(6,6)
c
c procedure
c clear array
      do 5 i=1,monoms
    5 ta(i)=0.d0
c put in new contents
      ta(7)=tm(1,1)
      ta(8)=tm(1,2)
      ta(9)=tm(1,3)
      ta(10)=tm(1,4)
      ta(11)=tm(1,5)
      ta(12)=tm(1,6)
      ta(13)=tm(2,2)
      ta(14)=tm(2,3)
      ta(15)=tm(2,4)
      ta(16)=tm(2,5)
      ta(17)=tm(2,6)
      ta(18)=tm(3,3)
      ta(19)=tm(3,4)
      ta(20)=tm(3,5)
      ta(21)=tm(3,6)
      ta(22)=tm(4,4)
      ta(23)=tm(4,5)
      ta(24)=tm(4,6)
      ta(25)=tm(5,5)
      ta(26)=tm(5,6)
      ta(27)=tm(6,6)
c
      do 10 i=7,27
  10  ta(i)=scale*ta(i)
c
      return
      end
c
***********************************************************************
c
      subroutine sndwch(t1a,t1m,t2a,t2m,t3a,t3m)
c this is a subroutine for sandwiching a map
c it computes t3=t1*t2*(t1 inverse)
c Written by Alex Dragt, Fall 1986
c Modified by Alex Dragt, 18 July 1988
c
      include 'impli.inc'
      include 'param.inc'
c
c calling arrays
      dimension t1a(monoms),t2a(monoms),t3a(monoms)
      dimension t1m(6,6),t2m(6,6),t3m(6,6)
c
c working arrays
      dimension ta(monoms)
      dimension tm(6,6)
c
      call mapmap(t1a,t1m,ta,tm)
      call inv(ta,tm)
      call concat(t2a,t2m,ta,tm,ta,tm)
      call concat(t1a,t1m,ta,tm,t3a,t3m)
c
      return
      end
c
***********************************************************************
c
      subroutine svpbkt(in,ord,psv,base, pb)
c  Single Variable Poisson BracKeT
c  Takes the poisson bracket of the order 'ord' part of 'in' with the
c  phase space variable represented by 'psv'.  The result is left in pb.
c  This subroutine replaces DRD's pbkt2 and was written by Liam Healy
c  on November 29, 1984 from an idea of Christoph Iselin.
c
c----Variables----
      include 'param.inc'
c  base = lowest index of pb
      integer base
c  in, pb = incoming array, outgoing pb array
      double precision in(*),pb(base:*)
c  ord = order of 'in' to be pb-ed
      integer ord
c  psv,wrt = phase space variable in pb,
c            variable to be diff with resp to
      integer psv,wrt
c  indin,indpb = indeces for 'in' and 'pb'
      integer indin,indpb
c  sign = multiplier +1 or -1 depending on whether x or p
c         differentiating
      double precision sign
      include 'expon.inc'
      include 'lims.inc'
c
c----Routine----
      if (mod(psv,2).eq.1) then
c  psv is a coordinate, diff wrt the canonical momentum and flip sign
        wrt=psv+1
        sign=-1.
      else
c  psv is a momentum, diff wrt the canonical coordinate
        wrt=psv-1
        sign=+1.
      endif
      indin=bottom(ord)
      do 120 indpb=bottom(ord-1),top(ord-1)
  100   if (expon(wrt,indin).eq.0) then
          indin=indin+1
          if (indin.le.top(ord)) goto 100
          return
        endif
        pb(indpb)=sign*expon(wrt,indin)*in(indin)
  120   indin=indin+1
      return
      end
c
***********************************************************************
c
      subroutine xform(f,no,m,matold,l)
c
c     Transforms a polynomial of degree no, f
c     by the lie transformation whose
c     matrix representation is m.  the coefficients
c     of the resultant polynomial are stored in the
c     the array l which thus contains the coefficients of f(m*z).
c
      include 'impli.inc'
      include 'param.inc'
      double precision l,m,f
      dimension f(monoms),l(monoms)
      double precision temp(monoms)
      dimension m(6,6)
c  expon = table of exponents
      include 'expon.inc'
c  vblist = table of variables occuring in monomial
      include 'vblist.inc'
c     
      include 'prodex.inc'
      include 'len.inc'
      include 'ind.inc'
c
c     initialise arrays
c
      do 10 kp=1,len(no)
      temp(kp) = 0.0d0
   10 continue
      do 100 n= len(no-1)+1,len(no)
        if(f(n).eq.0.0d0) goto 100
        do 101 kp=1,len(no-1)
          temp(kp) = 0.0d0
  101   continue
        do 102 k=1,6
          if(m(vblist(1,n),k).eq.0.0d0) goto 102
          temp(k) = f(n)*m(vblist(1,n),k)
  102    continue
        do 110 ior=1,no-1
          k1 = vblist(ior+1,n)
          if(ior.eq.1) then
            n1 = 1
          else
            n1=len(ior-1)+1
          endif
          do 112 k=1,6
            if(m(k1,k).eq.0.0d0) goto 112
            xm = m(k1,k)
cdir$ ivdep
            do 111 nn=n1,len(ior)
            temp(prodex(k,nn)) = temp(prodex(k,nn)) + temp(nn)*xm
  111       continue
  112     continue
  110   continue
  100 continue
      do 200 nn=len(no-1)+1,len(no)
        l(nn) = temp(nn)
  200 continue
c
      return
      end
c
c end of file
